# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Minify and deploy to Azure Web App - aberus

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Auto Minify
      uses: nizarmah/auto-minify@v1.3
      
    - name: compress-action
      uses: Charlesworth/compress-action@1.0.0
              
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aberus'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c0a55415d71a40ecbdca8bdf8330e576 }}
        package: .
