# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - aberus

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.103'
             
    - name: compress-action
      uses: Charlesworth/compress-action@1.0.0

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aberus'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_412d4d617af140218fc4c693bfdae584 }}
